name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test-rust:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown aarch64-linux-android
      - run: sudo apt-get update && sudo apt-get install libasound2-dev libudev-dev
        if: matrix.os == 'ubuntu'
      - run: make

  build-webassembly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Install wasm-opt
        run: brew update && brew install binaryen
      - run: make wasm
      - run: cd examples/gamepads-wasm-direct && make
      - run: cargo install wasm-bindgen-cli
      - run: cd examples/gamepads-wasm-bindgen && make

  check-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install uglify-js -g
      - run: make check-js

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
